import { it } from 'vitest';
import { installDiskFileSystem } from './helpers';
import { Scene3D } from '../src/blunted/scene/scene3d';
import { Vector3 } from '../src/blunted/base/math/vector3';
import { e_FunctionType, e_Velocity } from '../src/game/gamedefines';
import { AnimCollection, CrudeSelectionQuery } from '../src/game/onthepitch/player/humanoid/animcollection';
it('probe', () => {
  installDiskFileSystem();
  const anims = new AnimCollection(new Scene3D());
  anims.Load('media/animations');
  const all = anims.GetAnimations();
  const t = (label: string, f: () => void, runs = 2000) => { for (let i = 0; i < 200; i++) f(); const s = performance.now(); for (let i = 0; i < runs; i++) f(); console.log(label, ((performance.now() - s) / runs * 1000).toFixed(1), 'us'); };
  let c = 0;
  t('type compare', () => { for (let i = 0; i < all.length; i++) if (all[i].GetAnimType() === 'shot') c++; });
  t('getvariable x1', () => { for (let i = 0; i < all.length; i++) if (all[i].GetVariable('lastditch') === 'true') c++; });
  t('incoming velo', () => { for (let i = 0; i < all.length; i++) if (all[i].GetIncomingVelocity() > 1) c++; });
  t('incoming body dir angle', () => { for (let i = 0; i < all.length; i++) if (all[i].GetIncomingBodyDirection().GetAngle2D() > 1) c++; });
  const q = new CrudeSelectionQuery(); q.byFunctionType = true; q.functionType = e_FunctionType.e_FunctionType_Shot;
  t('crude type only', () => { const ds: number[] = []; anims.CrudeSelection(ds, q); });
  const q2 = new CrudeSelectionQuery();
  t('crude nothing', () => { const ds: number[] = []; anims.CrudeSelection(ds, q2); });
  const q3 = new CrudeSelectionQuery(); q3.byFunctionType = true; q3.functionType = e_FunctionType.e_FunctionType_Movement; q3.byIncomingVelocity = true; q3.incomingVelocity = e_Velocity.e_Velocity_Walk;
  t('crude movement walk', () => { const ds: number[] = []; anims.CrudeSelection(ds, q3); });
  q3.byIncomingBodyDirection = true; q3.incomingBodyDirection = new Vector3(0, -1, 0);
  t('crude movement walk bodydir', () => { const ds: number[] = []; anims.CrudeSelection(ds, q3); });
  console.log(c);
}, 60000);
